### ISSUE TITLE
about model structure

### ISSUE THREAD

**Issue by murdockhou** [VXallset/deep-high-resolution-net.TensorFlow#1]
Hi, thanks for your work.  The network output size is equal to the input, but i find the original pytorch implementation provided by author, the network output size is 1/4 about the input. So why do you write like this? thanks~

**Comment by VXallset** [comment]
Sorry for the late reply. 

As a matter of fact, I didn't dive into the author's pytorch implementation before implementing this repository, so I think this is the reason. 

You can modify the code in the `hrnet()` function to make the network output size to be a quarter of the input. To do that, you just need to modify the `output = output[0]` to be `output = output[2]`. As the HR-Net is a parallel network, you literally can get the same size, 1/2 of the input, 1/4 of the input or 1/8 of the input without modifying a lot of the code if you want. 

Hope this helpful.

**Comment by VXallset** [comment]
> Hi, thanks for your work. The network output size is equal to the input, but i find the original pytorch implementation provided by author, the network output size is 1/4 about the input. So why do you write like this? thanks~

@murdockhou 

Sorry for the late reply.

As a matter of fact, I didn't dive into the author's pytorch implementation before implementing this repository, so I think this is the reason.

You can modify the code in the `hrnet()` function to make the network output size to be a quarter of the input. To do that, you just need to modify the `output = output[0]` to be `output = output[2]`. As the HR-Net is a parallel network, you literally can get the same size, 1/2 of the input, 1/4 of the input or 1/8 of the input without modifying a lot of the code if you want.

Hope this helpful.

Regards.

**Comment by murdockhou** [comment]
@VXallset , thanks for your reply, this has been done. Thanks again~
