### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by AnasArram** [VXallset/deep-high-resolution-net.TensorFlow#13]
Can you please provide the pretrained model?

**Comment by VXallset** [comment]
@AnasArram 

Please go to the following address to fetch it. Enjoy~
 
https://pan.baidu.com/s/1bTmiP3MxxC17pF1S4pDpWQ  

Extraction code: 7hym

**Comment by AnasArram** [comment]
great, but can you please share a google drive link? because we have to register a new account in order to download it and there are many issues with this!

**Comment by study-renjie** [comment]
你好 百度网盘链接失效了，可以重新发一个吗？

**Comment by VXallset** [comment]
我刚试了一下没问题啊，你用这个看看

链接: https://pan.baidu.com/s/1Di3iyKlg8X2xp0q6ea_jtA 提取码: 7rz8

**Comment by VXallset** [comment]
@AnasArram 

> great, but can you please share a google drive link? because we have to register a new account in order to download it and there are many issues with this!

Sorry for the delay. Here is the google drive link:

https://drive.google.com/drive/folders/13ll_UyKLW31ozasChqzB_91sWEE4I2PZ?usp=sharing

Enjoy!

**Comment by AnasArram** [comment]
So cool, thanks a lot!
