### ISSUE TITLE
How can I download this dataset?Thank you so much!

### ISSUE THREAD

**Issue by SongQingChe** [VXallset/deep-high-resolution-net.TensorFlow#16]

**Comment by VXallset** [comment]
@SongQingChe  The AI challenger dataset is used for competitions and now it seems unavailable on their [web](https://challenger.ai/). Please go to [Baiduyun](https://pan.baidu.com/s/1VrpWOGc7dYnsNs22CqP38w) to get my copy.  Extraction code: x56v

**Comment by VXallset** [comment]
This can be closed.
