### ISSUE TITLE
what about multi-persons result?

### ISSUE THREAD

**Issue by uestcjackey** [VXallset/deep-high-resolution-net.TensorFlow#17]
I just learned that you directly predict all 14 points at diffirent 14 channels,but when there have multi-persons，how do you seprate them just by gauss points information?If you use a person detector or anything,thanks very much!!

**Comment by switchfootsid** [comment]
Loop through each predicted bounding box or multi-threaded inference for each one of crops.

**Comment by VXallset** [comment]
@uestcjackey 
The HR-Net is a top-down method, which means you need to use object detection algorithms such as [YOLO-v3](https://pjreddie.com/darknet/yolo/) to detect people in an image at first. Then for each predicted bounding box which contains only one person, applying the HR-Net. @switchfootsid is correct.

This can be closed.
