### ISSUE TITLE
test.py里面为何仍是train.tfrecord??

### ISSUE THREAD

**Issue by henbucuoshanghai** [VXallset/deep-high-resolution-net.TensorFlow#20]

**Comment by henbucuoshanghai** [comment]
aichallenger数据集没有测试集吗？tks

**Comment by VXallset** [comment]
@henbucuoshanghai 最近官网一直有问题，下载不了数据集，当时我下载的时候也只是有train那部分的能下载，test那部分没有提供。理论上你可以自己分一部分训练集做测试用，训练的时候只用一部分train里的图像，比如60%，测试的时候用20%，剩下的20%做validation。

**Comment by henbucuoshanghai** [comment]
可以，明白很细


再麻烦一次：请问论文里面有用此数据实验吗？ap有多高？好像没有。。。

**Comment by VXallset** [comment]
@henbucuoshanghai  记不太清了，好像只有COCO的和MPII的，你去找找
