### ISSUE TITLE
 the graphics memory（16 GB）, the max batch size I used was 2

### ISSUE THREAD

**Issue by henbucuoshanghai** [VXallset/deep-high-resolution-net.TensorFlow#3]
the graphics memory（16 GB）, the max batch size I used was 2

2 is too small,  16G???????????

**Comment by VXallset** [comment]
You can try different batch size of course as long as it doesn't crash. I guess my implementation is not efficient enough and/or the HR-Net itself is too complicated.

**Comment by VXallset** [comment]
> the graphics memory（16 GB）, the max batch size I used was 2
> 
> 2 is too small, 16G???????????

Hi henbucuoshanghai,
You can try different batch size of course as long as it doesn't crash. I guess my implementation is not efficient enough and/or the HR-Net itself is too complicated.
