### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by henbucuoshanghai** [VXallset/deep-high-resolution-net.TensorFlow#5]
File "/home/li/deep-high-resolution-net.TensorFlow/src/heatmap.py", line 83, in decode_pose
    images[b,:,:,:]= draw_lines_on_img(images[b], point_ver, point_hor, point_class)
TypeError: list indices must be integers or slices, not tuple

**Comment by henbucuoshanghai** [comment]
why

**Comment by VXallset** [comment]
> File "/home/li/deep-high-resolution-net.TensorFlow/src/heatmap.py", line 83, in decode_pose
> images[b,:,:,:]= draw_lines_on_img(images[b], point_ver, point_hor, point_class)
> TypeError: list indices must be integers or slices, not tuple

Please debug it and check the value of the variable b

**Comment by henbucuoshanghai** [comment]
i used your model from email,but it detected nothing in cxk.jpg     why。。。。

**Comment by VXallset** [comment]
> i used your model from email,but it detected nothing in cxk.jpg why。。。。

Change the threshold from 0.001 to be 0 and try again.
`timgs = decode_pose(_img, tnet_output, threshold=0.001)`

**Comment by henbucuoshanghai** [comment]
the code detect one img       ?
the net detect the img,and output is 0 array,..

**Comment by VXallset** [comment]
> the code detect one img ?
> the net detect the img,and output is 0 array,..

I updated the code. Please try the _temp.py_, it works smoothly on my machine.
