### ISSUE TITLE
hrnet单人的姿态

### ISSUE THREAD

**Issue by henbucuoshanghai** [VXallset/deep-high-resolution-net.TensorFlow#6]
多的人效果不好                        那摄像头里面尽量一个人占据整个屏幕  ？？？？？      多人怎么办？  检测一段视频，画面多人，怎么办呢？

**Comment by VXallset** [comment]
> 多的人效果不好 那摄像头里面尽量一个人占据整个屏幕 ？？？？？ 多人怎么办？ 检测一段视频，画面多人，怎么办呢？
@ henbucuoshanghai 官方的做法是在这个网络前面加上一个目标监测网络（例如Yolo V3），提取多个包含人体的区域，每个区域只有一个人。然后对每个区域分别用HRNet作人体姿态估计。

**Comment by VXallset** [comment]
> 多的人效果不好 那摄像头里面尽量一个人占据整个屏幕 ？？？？？ 多人怎么办？ 检测一段视频，画面多人，怎么办呢？


@henbucuoshanghai 

官方的做法是在这个网络前面加上一个目标监测网络（例如Yolo V3），提取多个包含人体的区域，每个区域只有一个人。然后对每个区域分别用HRNet作人体姿态估计。

**Comment by henbucuoshanghai** [comment]
那人体姿态很难实时。。。

**Comment by VXallset** [comment]
> 那人体姿态很难实时。。。

@henbucuoshanghai 的确。如果想实时的话必须要满足两点，1. 模型足够精简， 2. 机器性能良好。你可以去试试[simple HRNet](https://github.com/stefanopini/simple-HRNet)， 这个是用pyTorch实现的精简的HRNet，需要先去下载Yolo V3的代码和模型。但是即使是使用simple HRNet，我在RTX2080的机器上测得也只有17帧/s，依旧达不到实时(30帧/s)的要求。HRNet本身由于是并行的网络，比其他模型要复杂。要想用HRNet还要实时的话只能使用算力更强的机器......

**Comment by henbucuoshanghai** [comment]
回复的好详细，多谢
那先yolo3训练coco数据集，检测图片的人体   然后摄像头先调用yolo3检测人体，人体一个个给hrnrt，画出姿态，然后显示在原视频里？

**Comment by VXallset** [comment]
> 回复的好详细，多谢
那先yolo3训练coco数据集，检测图片的人体   然后摄像头先调用yolo3检测人体，人体一个个给hrnrt，画出姿态，然后显示在原视频里？

@henbucuoshanghai 是这样的。好像TensorRT可以在推理的时候进行加速，说不定可以满足实时的要求，可以去研究研究。

**Comment by henbucuoshanghai** [comment]
是的  是工业的方向   肯定实时        那大佬发论文姿态有什么好方向吗？
