### ISSUE TITLE
一块卡训练AI challenre  train需要多久呢？十多天？

### ISSUE THREAD

**Issue by henbucuoshanghai** [VXallset/deep-high-resolution-net.TensorFlow#7]

**Comment by VXallset** [comment]
@henbucuoshanghai 
看你的显卡算力，还有你要训练多少个epoch。这个只能实测，不太好估计。给你个参考值吧。用这个代码跑一个epoch在RTX2080上要3天，在两个Titan V上要30个小时。

**Comment by henbucuoshanghai** [comment]
好吃资源     那姿态这一块很耗gpu，是这样的是吧。。
