### ISSUE TITLE
calculate_OKS？

### ISSUE THREAD

**Issue by henbucuoshanghai** [VXallset/deep-high-resolution-net.TensorFlow#8]
what is it?

**Comment by VXallset** [comment]
> what is it?

@henbucuoshanghai 
Object keypoint similarity. Please refer to [this](http://presentations.cocodataset.org/COCO17-Keypoints-TeamOKS.pdf)

**Comment by henbucuoshanghai** [comment]
我水平好菜，现在搞姿态。。   发愁

**Comment by henbucuoshanghai** [comment]
我水平好菜，现在搞姿态。。   发愁
