### ISSUE TITLE
threadhold 0.01  

### ISSUE THREAD

**Issue by henbucuoshanghai** [VXallset/deep-high-resolution-net.TensorFlow#9]
where is it come from?

**Comment by VXallset** [comment]
> where is it come from?

Empirical value.

**Comment by henbucuoshanghai** [comment]
from (x,y) point  to heatmap ,the code is right？
and max_index//192 is row             max_index%192 is col      i dont understand

**Comment by OriginalV** [comment]
> from (x,y) point to heatmap ,the code is right？
> and max_index//192 is row max_index%192 is col i dont understand

np.argmax(matrix) get the index of the max value in matrix, the index has one dimension and equals to row*n+col

**Comment by henbucuoshanghai** [comment]
equals to row*n+col

why

**Comment by VXallset** [comment]
> equals to row*n+col why

@henbucuoshanghai 

It is a converting between the 1D vector and 2D array. Imagine a 2D matrix a, whos value is 
`[[1, 2, 3]`
`[4, 5, 6]`
`[7,8,9]`
`[10, 11, 12]]`

so the np.argmax(a)=11, it means the max value is the 12th number of the matrix. the coordinate of the 12th value is : x = 11//3=3, y = 11%3=2, therefore its coordinate is [3, 2], namely the 4th row and 3rd col, vise versa.

**Comment by henbucuoshanghai** [comment]
oh ,nice answers   thanks,i know    .
thanks for all the  hep here.thanks
